services:
  bill-splitter:
    image: golang:1.26
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    ports:
      - "8080:8080"
    networks:
      - proxy
      - bill-splitter
networks:
  proxy:
    external: true
  bill-splitter:
    external: true
